### ISSUE TITLE
Next release send2cgeo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#102]
I do see quite some PRs have accumulated for this repo.

 @capoaira 
Do we need to follow any sequence for merging those?

I would like to start with testing and releasing with #95 as it is a more generic change.
On what code status did you base the other PRs?

**Comment by capoaira** [comment]
>  Do we need to follow any sequence for merging those?

Not really. But #100 must be merged before #101 


> On what code status did you base the other PRs?

What do you mean with code status? I did nothing else than usual.

**Comment by Lineflyer** [comment]
> What do you mean with code status? I did nothing else than usual.

Sorry for being unprecise:
I guess if we merge #95 this will produce conflicts with all other PR except if you based one on another in a certain sequence.
So I think lets merge #95 first and you need to rebase the others anyway.

**Comment by capoaira** [comment]
Ah ok. Sorry my english is not the best...

> So I think lets merge #95 first and you need to rebase the others anyway.

Yes 👍🏻

**Comment by Lineflyer** [comment]
New functions and general functionality tested ok with Firefox and Chrome.
`release` has been fast forwarded to `master`, so version 0.50 is live now.

Thanks @capoaira
