### ISSUE TITLE
Add Owner Dashboard

### ISSUE THREAD

**Issue by capoaira** [cgeo/send2cgeo#107]
There are a new page for cacheowners (https://www.geocaching.com/play/owner) with new lists:
https://www.geocaching.com/play/owner/published
https://www.geocaching.com/play/owner/unpublished
https://www.geocaching.com/play/owner/archived
Here I would add s2cgeo-buttons

**Comment by Lineflyer** [comment]
I found time to test the owner dashboard function on master.
Seems to be working. Need to make some regression tests of other pages though.

Still lets wait a bit until rollout due to #97 in case a solution comes in.
