### ISSUE TITLE
Retrieve icon from website ressource

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#113]
The script could/should be changed to retrieve its icon from https://www.cgeo.org/send2cgeo.png

The icon has been reworked recently and is now available under this URL.

**Comment by bekuno** [comment]
> I like the new Icon. Should we use it also for the buttons?

Yes!

**Comment by Lineflyer** [comment]
Oh yes, forgot that. Feel free to submit a PR. Version 0.52 is still open for publishing.
