### ISSUE TITLE
Result window not visible

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#120]
Found while testing change #118 as fix for #117 

The send2cgeo icon is now shown in the sidebar, however I have noticed, that the result window after sending a cache is either not working or placed to high:
![grafik](https://user-images.githubusercontent.com/949669/100863608-190d3700-3495-11eb-993c-271cec5ae6e1.png)

Not sure if it is a regression but should be checked if possible to solve.
@capoaira

**Comment by capoaira** [comment]
I think that could be resolved with an z-index. I'll prepare a PR

**Comment by capoaira** [comment]
Not solved with `z-index`. Fixed with `top` in #116
