### ISSUE TITLE
Send2cgeo release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#121]
Due to changes #84 and #117 a new send2cgeo version should be released.

While testing above mentioned changes I stumbled upon #120 where I am not sure, whether it is a regression.
Still IMHO this problem is not blocking a release as function is OK only a cosmetic problem.

@capoaira Can you take a look on #120 else I might release a new version anyway and we can try to solve this in a release afterwards.

**Comment by capoaira** [comment]
Can somebody have a look at #124 so that the new version can be released?

**Comment by Lineflyer** [comment]
Will do as time permits. Thanks for the reminder.

**Comment by Lineflyer** [comment]
Looks all good to me. Nice new features.
I did however only test in Firefox/Tampermonkey combination but not with Google Chrome as I had no time for that.

Will release soon.

**Comment by Lineflyer** [comment]
Release of send2cgeo script 2021.02.16 was done (`master` has been merged to `release` which should trigger update of installed scripts).
Thanks @capoaira for keeping this alive and improving it!!!
