### ISSUE TITLE
Add "Send2cgeo" to right click menu of caches at the live map

### ISSUE THREAD

**Issue by fm-sys** [cgeo/send2cgeo#129]
![grafik](https://user-images.githubusercontent.com/64581222/114733432-9ac67880-9d43-11eb-811b-60c214b816a2.png)

A "Send2cgeo" button would be pretty awesome in that right click menu ;-)

**Comment by capoaira** [comment]
My first try for this works a few Day or weeks. Than GS updated the Map and it was working anymore...
Maybe I can give a second try.

**Comment by fm-sys** [comment]
Thank you @capoaira for fixing this 👍
