### ISSUE TITLE
The cookie "browser_code" will soon be rejected (firefox)

### ISSUE THREAD

**Issue by capoaira** [cgeo/send2cgeo#132]
On sending caches I get this warning message in the console:
English (translated)
`
The cookie "browser_code" will soon be rejected because it specifies either "None" or an invalid value for the attribute "SameSite" without using the "secure" attribute. For more information on the "SameSite" attribute, see https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.
`
German (original):
`
Das Cookie "browser_code" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.
`
I don't know how soon they will reject the cookie.

I think the workaround #112 will be work also for firefox, but it is not as beautiful as the popup.
It look like we have to find a solution for #12. Maybe #53 (this would also fix #48))
Or Maybe it is possible to use the "secure"-Attribut for the cookie, but also this has to happend on the Server.

**Comment by Lineflyer** [comment]
@capoaira 
Now it seems to be the case, that send2cgeo fails to work on the most recent Firefox version. Activating the Chrome workaround #112 solves it also for Firefox.

Would you be willing to help to make this the new default behavior so it works "Out of the box" for both Firefox and Chrome?

Other more generic solutions like #12 in #53 would also be welcome, but probably sound like much work.

**Comment by capoaira** [comment]
> Would you be willing to help to make this the new default behavior so it works "Out of the box" for both Firefox and Chrome?

Yes

> Other more generic solutions like #12 in #53 would also be welcome, but probably sound like much work.

Yes, I think so too. Maybe you can upload the current code from https://send2.cgeo.org/, so I can see how it actually works and try to implement an API (or something similar as "quick and dirty"-solution). But I've never programmed an API myself, so I can't promise anything.

**Comment by capoaira** [comment]
I create a PR.
I think on https://www.cgeo.org/send2cgeo the "Special setting for Google Chrome" can be removed.

**Comment by Lineflyer** [comment]
@mucek4 
I believe there is still the open issue to publish the server side code of send2cgeo to this repo?!
