### ISSUE TITLE
Columns are moved ugly on search page if member is a basic member.

### ISSUE THREAD

**Issue by 2Abendsegler** [cgeo/send2cgeo#133]
Columns are moved ugly on search page if member is a basic member.
No other scripts running.

1. Sign in as a basic member.
2. Go to [search page](https://www.geocaching.com/play/search).
3. Click on search button.
4. See column problem.

![grafik](https://user-images.githubusercontent.com/22332216/119254622-a49b9100-bbb7-11eb-9348-86e74de35747.png)

FF 88.0.1 (64-Bit), Win 10

**Comment by capoaira** [comment]
Den Bug hatte ich schonmal behoben. Das ist etwas, was in s2cg behoben werden müsste.

**Comment by capoaira** [comment]
Ups, I can not read ;)
I'll try to fix that

**Comment by capoaira** [comment]
If fix that bug @2Abendsegler here is the test version #134

@Lineflyer It would be good if this fix were released quickly.

**Comment by 2Abendsegler** [comment]
@capoaira 
My tests were successful.
Great job. 😊

**Comment by Lineflyer** [comment]
@Lineflyer Will do tonight after short test run.

**Comment by Lineflyer** [comment]
Thanks @2Abendsegler for reporting and @capoaira for fixing.
Briefly tested it as BM and PM and found no regressions. Will set it live in a minutes as script version 2021.05.23.
