### ISSUE TITLE
Send2cgeo issue

### ISSUE THREAD

**Issue by deniel13** [cgeo/send2cgeo#136]
Hello, I have the Tampermonkey extension fully installed (on Chrome) with the script Send2cgeo script selected as enabled.  The browser (Chrome) and device (Samsung Galaxy 6) are registered.

There are two issues. One, when I click on "send to c:geo," I'm told to "Register First." I click on that link, and I can see my created UN and PW, so I'm sure I'm registered.

I understand that Chrome requires a workaround in that on my dashboard on geocaching.com, in that there should be a link called, “send2cgeo settings." This isn't anywhere on my geocaching.com dashboard.

Is there a VPN issue I need to know about? I checked my authorizations and I didn't see any options there.

Any help would be appreciated,

Daniel

**Comment by Lineflyer** [comment]
> I understand that Chrome requires a workaround in that on my dashboard on geocaching.com, in that there should be a link called, “send2cgeo settings." This isn't anywhere on my geocaching.com dashboard.

The link to the settings page should be here (as shown):
![image](https://user-images.githubusercontent.com/949669/131232605-637515a9-276b-4034-a193-520d16d4d629.png)

Did you use send2cgeo before and it failed or are you first time trying to get it going?

**Comment by deniel13** [comment]
Thank you for the screenshot. Found it. Tested it and things seem to be in
order. As for c:geo itself, where would I find the sent cache? Thanks!


*Daniel **Blattner, **Esq.* <https://www.youtube.com/watch?v=yZIummTz9mM>

**Comment by Lineflyer** [comment]
Open any list in c:geo and select Menu - Import - Import from send2cgeo

**Comment by deniel13** [comment]
Gotcha; actually has to be in list mode..thanks for your help!


*Daniel **Blattner, **Esq.* <https://www.youtube.com/watch?v=yZIummTz9mM>
