### ISSUE TITLE
Send2cgeo load multiple caches on one click

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#14]
_From @triakcz on October 19, 2011 13:17_

Hi, It'll be great when cgeo can load many caches on one click, it could be implemented same way as waypoint download from geocaching.com search results. If it is possible to add button there It'll be useful. Thanks I'm not so good in javascript so I had tryed but I can't do that.

_Copied from original issue: cgeo/cgeo#689_

**Comment by Lineflyer** [comment]
_From @toze3 on June 25, 2012 14:8_

Hi.

yes this could be a nice feature. Maybe a creation in the browser of lists, and then the option to import these list in C:GEO with automatic creation of lists or importing to a list with the same name. 

Best regards

**Comment by chaelli** [comment]
I just had the need to send all caches of a country. The list is about 20'000 caches long. I used the new search-results page and the following script (which you might be able to integrate into the tampermonkey/greasmonkey script):

```javascript
function loadCachesAndSubmit(currentStart) {
	jQuery.get("https://www.geocaching.com/play/search/more-results?startIndex="+currentStart+"&inputOrigin="+resultsParams.inputOrigin+"&sortOrigin="+resultsParams.homeCoords+"&fbu=false&filteredByOtherUsersFinds=false&filteredByOtherUsersFindsUsername=&originTreatment="+resultsParams.originTreatment, function(data) {
		jQuery("a[href*='http://www.geocaching.com/geocache/GC']", jQuery(data.HtmlString)).each(function() {
			var cachenr = jQuery(this).attr("href").replace("http://www.geocaching.com/geocache/","");
			jQuery.getScript("https://send2.cgeo.org/add.html?cache=" + cachenr);
		});
		if (data.ShowLoadMore) {
			loadCachesAndSubmit(currentStart + 50);
		}
		else {
			alert("Finished sending");
		}
	});
}
loadCachesAndSubmit(0);
```

**Comment by Lineflyer** [comment]
As @arminus was asking us if we could implement a batch transfer of caches in send2cgeo and maybe willing to implement it, we should maybe think about publishing the server code into this repository as well?!

**Comment by SammysHP** [comment]
AFAIK the server code needs a review and probably some refactoring before it can be made public.

**Comment by mucek4** [comment]
Think is we moved our webpage to github. By the time we just disabled the old webpage but couldn't disable server code for send2cgeo. The main problem is core of webpage and send2cgeo is the same, so technically old webpage still has to be running in background for send2.
Basically send2cgeo needs to be re-written (parts could be copy-pasted)

**Comment by mirabilos** [comment]
For future reference, I managed to do it, thanks to the hints from the posters above (thanks!), by opening Firebug (F11) on GC.COM and copy/pasting a line like the following into the `Konsole` tab of Firebug:

    jQuery.each(["GC4HNPP","GC5QK6Y", …, "OC1424A","OC14357","OC1438D"], function (k,v) { jQuery.getScript("https://send2.cgeo.org/add.html?cache=" + v); })

(I’ve shortened the line, just list all the caches you want there.)

Then, I ignored all console warnings. A proper webinterface would be more welcome, though, of course.

**Comment by Lineflyer** [comment]
Partially implemented with bff566fd72a4768df16fd590c316ce920359ee17 in version 0.45

**Comment by mirabilos** [comment]
Doesn’t help my use case, as I never use the search page. At best the map, or I have a list of caches as text file.

But if it helps someone else… sure.

**Comment by capoaira** [comment]
I tried something. What do you think? 
With the link in the dashboard you can send a list of gccodes to c:geo.

![grafik](https://user-images.githubusercontent.com/50927164/72669030-442d9a00-3a2d-11ea-9f5d-c2d9290ea581.png)
https://github.com/capoaira/send2cgeo/raw/Send2cgeo-load-multiple-caches-on-one-click/send2cgeo.user.js

**Comment by capoaira** [comment]
I tried something. What do you think? @triakcz @mirabilos 
With the link in the dashboard you can send a list of gccodes to c:geo.

![grafik](https://user-images.githubusercontent.com/50927164/72669030-442d9a00-3a2d-11ea-9f5d-c2d9290ea581.png)
https://github.com/capoaira/send2cgeo/raw/Send2cgeo-load-multiple-caches-on-one-click/send2cgeo.user.js

**Comment by mirabilos** [comment]
I don’t use the dashboard, and this would only work for GC.COM users anyway.

I’d rather have it near the box on https://www.cgeo.org/send2cgeo.html as it’ll take a list of waypoint codes and therefore is independent of the platform.

**Comment by capoaira** [comment]
It would be not a problem to implement this feature also at OC. Or at https://www.cgeo.org/send2cgeo.html
It make no difference if you send a GC- or a OC-Code.

**Comment by capoaira** [comment]
Hello,
Since sending a GC code list has been requested many times, I implemented this feature today.

You can test the function here: https://github.com/capoaira/send2cgeo/raw/send-multiple-caches/send2cgeo.user.js

Here it goes back to the current version: https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js

How to use the function:
Click the "Send List" link. You can find this link on geocaching.com in the new and old dashboards under the renewal date and on opencaching.de at the top of your profile (https://www.opencaching.de/myhome.php).
Then a popup will open where you can insert your list and send it.
The seperator is irrelevant, it can be spaces, commas, line breaks, etc.
