### ISSUE TITLE
Columns unaligned on owned caches list if website runs in Italian language

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#140]
User report on support mail (ticket 860217):

- Use the geocaching website in Italian language with activated send2cgeo script (version 2022.01.16) and open the URL https://www.geocaching.com/play/owner/published (did not check whether other lists are affected as well).
- The following wrong column order is shown (Note: 
![grafik](https://user-images.githubusercontent.com/949669/190088514-7bc93e22-e8c0-486f-81ab-994ba8b96256.png)
The problem here is, that no column header for the sed2cgeo icon is inserted, therefore making all column headers unaligned to their content (shifted one to the left).
- Switch sends2cgeo off and reload the page shows how it should look like:
![grafik](https://user-images.githubusercontent.com/949669/190088675-4956ef75-d5ee-4ccc-8222-f991eca6578a.png)

If the website is switched to English language its working normal:
- Send2cgeo on:
![grafik](https://user-images.githubusercontent.com/949669/190088845-0e9dd1a3-bc70-4951-a651-53b0b6367d59.png)
- Send2cgeo off:
![grafik](https://user-images.githubusercontent.com/949669/190088960-da3f8585-b6dc-4827-b7f0-22be5384e83d.png)

**Comment by capoaira** [comment]
Oh, I cannot believe, that the class names in the source code are also translated... I'll never understand the GS developers... In German and English it works, but in all other languages where "name" is not wrote "name" it doesn't work.
