### ISSUE TITLE
Send2geo unsupported by Google Chrome?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/send2cgeo#145]
Ticket #445690

We have a support ticket claiming that send2geo is supposedly unsupported by Google Chrome in the future. 

Is this true? If yes: is there something we can do about it?

Original user request (German):

habe heute eine Nachricht von Google Chrome erhalten, daß die Erweiterung sendtocgeo bald nicht mehr unterstützt wird. Macht ihr da ein Update oder wie kann man sich das in weiterer Zukunft vorstellen. Ich persönlich verwende die Erweiterung regelmäßig und es wäre mehr als ärgerlich, wenn das nicht mehr funktioniert.

https://chromewebstore.google.com/detail/send2cgeo/baflojfpgicbegbdfaklkhnjoikendeh

**Comment by capoaira** [comment]
This repo is not a browser extension, so afaik we can not do something against it.
Maybe the extension is from the issue author of #32

**Comment by eddiemuc** [comment]
Thanks, I passed the info to the user. Closing here
