### ISSUE TITLE
Wording in send2cgeo iframe

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/send2cgeo#17]
"Browser not registrated" should be "Browser not registered".
"Registrated!" should be "Registered."
typo in "you can set a name fot it" (for)
typo in "was succesfully added" (missing "s" in successfully)

**Comment by Lineflyer** [comment]
You are refering to the iframe on our homepage?!
I adapted the title and set the label "Server related". Please correct me if my assumption was wrong.

**Comment by Bananeweizen** [comment]
Completely correct. Therefore I assigned @mucek4 instead of just changing some .md file.

**Comment by mucek4** [comment]
I think I did it.
