### ISSUE TITLE
confusion

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/send2cgeo#18]
There are three links from the send2cgeo homepage to the repo, 2 of them pointing to master, one to release. I guess they should all point to release?

Why is the script source duplicated in the root directory and the "chrome-extension" sub directory? I totally don't know which one to edit now. If the one in chrome-extension is deprecated, it should be deleted. If it needs to be there for building a chrome extension, then it should also be deleted, but a small ant script be added to copy it from the root directory.

**Comment by Lineflyer** [comment]
Up to my knowledge we dropped the work on extensions and decided to just continue with the script and make use of Greasemonkey/Tampermonkey so IMHO thos3 subdirs can be deleted.

Regarding the links:
I might not have seen those other links. In fact all of them should point to release on this repo.
