### ISSUE TITLE
send2cgeoOC doesn't work

### ISSUE THREAD

**Issue by Slini11** [cgeo/send2cgeo#29]
The script doesn't display the send2cgeo-button on the opencaching viewcache page (ff, 47.0.1).
Send2cgeo is not even executed if I visit the opencaching.de viewcache page (but Greasemonkey is active and the script is installed).
OC had supported https since Feb. 2016 but I thinks that's not the resason & only another problem?
See the report at the opencaching-forum: http://forum.opencaching.de/index.php?topic=4392.msg58927#msg58927

**Comment by Bananeweizen** [comment]
I assume you had installed the GC only script, while OC needs a separate script. Updated instructions to avoid that. Please reopen if the issue remains.
