### ISSUE TITLE
send2cgeo - Stuck on multi cache import 

### ISSUE THREAD

**Issue by akkatracker** [cgeo/send2cgeo#33]
Duplicating @bockyPT 's issue in the main cgeo repo cgeo/cgeo#6146 in case it's an issue with the script:

#### Detailed steps causing the problem:

    - On my PC I added a bunch of caches to the "send2cgeo" import queue;
    - On my Android 6 phone I tried to import them to a list;

#### Actual behavior after performing these steps:

    It imported a lot of caches correctly, but is now stuck on cache GC11CPZ - maybe it's related to its name starting with a "#"?

#### Expected behavior after performing these steps:

    Every cache should be properly imported.

#### Version of c:geo used:

2016.11.05
#### Is the problem reproducible for you?

Yes
#### System information:

Browser: Chrome 54.0.2840.71 m (64-bit)
Extension: Tampermonkey 4.1.10 with Send to c:geo 0.37
Phone: Xiaomi Redmi 3S Prime running Android 6.0.1 MMB29M (MIUI 8 Global 6.9.8 Beta)

**Comment by Lineflyer** [comment]
Closing due to lack of feedback from submitter.
