### ISSUE TITLE
Release button fix for Opencaching.de

### ISSUE THREAD

**Issue by FriedrichFroebel** [cgeo/send2cgeo#35]
I sent a fix for the missing button on Opencaching.de some time ago which has been merged into the `master` branch in February.

During a [discussion inside the Opencaching.de forum](https://forum.opencaching.de/index.php?topic=4635.msg60790#msg60790) I got aware of the fact that I still has not been pushed to the `release` branch to fix the existing installations. Is there a special reason why this has not been done until today?

**Comment by Bananeweizen** [comment]
probably a simple oversight, and merely none of the developers actually using that script by themselfes (therefore not seeing any issue remain). I just merged. The version number was already increased, so browsers should fetch the update on their own then.
