### ISSUE TITLE
send2cgeo for opencaching.de does no longer work

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#4]
_From @rsudev on November 26, 2014 19:52_

As the website removed the button which is our anchor point, the send2cgeo button is no longer shown (cross-check other oc-nodes as well!)

_Copied from original issue: cgeo/cgeo#4498_

**Comment by Bananeweizen** [comment]
Works fine for me with the OC version of the script (which is only available in the repo).
