### ISSUE TITLE
extended line height for premium caches in basic member list view

### ISSUE THREAD

**Issue by BMWHoizer** [cgeo/send2cgeo#44]
testing enviroment: FF54 with tampermonkey or greasemonkey
premium caches in basic member list view looks like follow:

![gc-bmview040](https://user-images.githubusercontent.com/29816235/27997128-ea7da71a-64f1-11e7-985c-8779a6280a7c.png)

**Comment by Lineflyer** [comment]
Confirmed, however I have currently no idea how to tackle this.
