### ISSUE TITLE
Remove PL script

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/send2cgeo#45]
Today I learned via an [OC.DE discussion](https://forum.opencaching.de/index.php?topic=4921.0) that at least OC.PL has a native send2cgeo functionality. We should therefore remove the PL script. Is there any good way to phase out a userscript? I'm thinking of
* making users aware they can and should uninstall it
* avoiding trouble with the update mechanism, if we delete it.

![image](https://user-images.githubusercontent.com/406876/31110676-0bb9490c-a809-11e7-9bfe-56f65520bbdd.png)

**Comment by mucek4** [comment]
Make a new "empty" version?

**Comment by capoaira** [comment]
```javascript
// @include        http://www.opencaching.nl/viewcache.php*
// @include        https://www.opencaching.nl/viewcache.php*
```

It looks like the pl script also supports opencaching.nl.
But for nl it does not work:
![grafik](https://user-images.githubusercontent.com/50927164/74690105-0bc0dd80-51de-11ea-81a0-e6cf2ef72a96.png)
