### ISSUE TITLE
Is send2cgeo compatible with Greasmonkey 4

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#47]
A user contacting us on support is reporting, that with Firefox version >=57 Greasemonkey needs to change their code to get compatible.
This seems to come along with some rare not backward compatible changes.

No idea if send2cgeo is affected. Can someone check?

https://arewewebextensionsyet.com/

http://www.greasespot.net/2017/09/greasemonkey-4-announcement.html

**Comment by SammysHP** [comment]
send2cgeo should work with Tampermonkey which is already compatible with Firefox. Not sure about how fast Greasemonkey will be available as a webextension.

**Comment by Lineflyer** [comment]
So after upgrading Firefox to V57.0 and corresponding upgrade of Greasemonkey to V4 I tested send2cgeo and all functions seem to work normally.

IMHO we can close this.

**Comment by Lineflyer** [comment]
BTW:
Seems I should change to Tampermonkey nontheless as following scripts seem to fail (in their current versions) on Greasemonkey V4:
- Project GC
- GClh II
