### ISSUE TITLE
Send2cgeo button missing on cache detail page

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#49]
Example cache: https://www.geocaching.com/geocache/GC5Z8KY_sb7-la-grotte-secrete-sentier-botanique?guid=5b31e712-f921-4122-8914-03bcfa47221c

Environment
Firefox 57.0
Tampermonkey 4.5.5633
Send2cgeo V0.4

Possibly related to recent website changes

**Comment by IiroP** [comment]
Working for me, 
Firefox 58.0
**Grease**monkey 4.1
Send2cgeo 0.4

**Comment by vicarvernon** [comment]
Not working for me
Firefox 58.0.1
Greasemonkey 4.2
send2cgeo ?
script doesn't load, just listed on a webpage

**Comment by Lineflyer** [comment]
This issue is no longer reproducible.
