### ISSUE TITLE
Success message opens in new window or is not shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#54]
Transfering issue to the right repository:

In https://github.com/cgeo/cgeo/issues/7105 users reported, that when using send2cgeo on geocaching.com the "Success" message is either not shown or (tested myself) is opening as full page (URL: https://send2.cgeo.org/add.html?cache=GCxxxx) instead.

I also tested a one year old version of the send2cgeo script (0.40) with the same result. So it looks, this issue is caused by a changed behavior of the website.

**Comment by wizard4u** [comment]
any progress to be expected ?

**Comment by Lineflyer** [comment]
I am sorry, that I cannot help. But I am not familiar with script language and the working mode. At the moment there is not much activity around here, so lets hope someone can help.

**Comment by mariansam** [comment]
Temporary solution: https://github.com/mariansam/gc-send2cgeo-success

**Comment by mucek4** [comment]
@mariansam if you have time you can fix the issue and open a pull request.

**Comment by mariansam** [comment]
@mucek4 I would like to, but I don't have time and experience. The "Temporary solution" is just one-line userscript.

**Comment by Lineflyer** [comment]
I was able to find a fix.
Seems the script used a depracted jquery function.

PR sent and needs to be merged. Afterwards `master` needs to be merged to `release` to make the update available to users.
