### ISSUE TITLE
send2cgeo

### ISSUE THREAD

**Issue by wizard4u** [cgeo/send2cgeo#58]
Send2cgeo gives error:
https://send2.cgeo.org/add.html?cache=GC7TDHN werkt even niet, of de pagina kan verhuisd zijn naar een nieuw webadres.

translated: does not work now or the page is moved to a new webaddress

New chrome version
Google Chrome is up-to-date
Versie 74.0.3729.157 (Officiële build) (64-bits)

**Comment by mucek4** [comment]
For today I think it's good. But work is not done yet. send2 is a legacy code that sadly does not work on new server. I believe it needs re-factoring or actually re-write.

**Comment by ave72** [comment]
Is this still an active issue? Opening the link (wizard4u, May 18, 2019) will immediately send the GC to my mobile.

If it's not active anymore, can it be closed then?

**Comment by wizard4u** [comment]
sorry, is solved from my perspective.

**Comment by bekuno** [comment]
@mucek4 

> For today I think it's good. But work is not done yet. send2 is a legacy code that sadly does not work on new server. I believe it needs re-factoring or actually re-write.

Is it finished yet?
I think you should open a new issue when changes in infrastructure or server(code) are required.

**Comment by mucek4** [comment]
For now I Dockerize it and it runs on "legacy" code. But a but long term solution is needed. I'll open issue.
