### ISSUE TITLE
Send2cgeo does not work with new geocaching map

### ISSUE THREAD

**Issue by bekuno** [cgeo/send2cgeo#63]
There is a completely new structure in the sidebar than in the old map implementation.

Address: https://www.geocaching.com/play/map

**Comment by capoaira** [comment]
I have try something:
![grafik](https://user-images.githubusercontent.com/50927164/72616739-d5224980-3937-11ea-9dba-79b7579e834d.png)

Is that okay?

**Comment by bekuno** [comment]
LGTM :-)
