### ISSUE TITLE
send2cgeo only works in english on the browsemap

### ISSUE THREAD

**Issue by capoaira** [cgeo/send2cgeo#68]
If geocaching.com on german or an other language the link for s2cg don't added to the details template in the old map

Maybe wie have to work with a mutation observer.

**Comment by capoaira** [comment]
When #86 is merged, I make a PR with the fix for this Issue

**Comment by Lineflyer** [comment]
Fixing this makes not too much sense for the time being as c:geo downloading the send cache will switch the website to english anyhow.

**Comment by capoaira** [comment]
If you use the GClh, you can set geocaching.com automatically to german. 
I was wrong when I'm writing that the Mutation Observer is necessary. So it is not a difficult bug.
