### ISSUE TITLE
support new list page

### ISSUE THREAD

**Issue by capoaira** [cgeo/send2cgeo#69]
The new list page https://www.geocaching.com/plan/lists is not supported by s2cg
An implementation like GCTor would be nice.

**Comment by Lineflyer** [comment]
@capoaira 
I tried to test this change but have a question:
When I look onto the overview page of the bookmark lists https://www.geocaching.com/plan/lists/ I do not find any send2cgeo option.
Only on the bookmark lists itself, like on https://www.geocaching.com/plan/lists/BM4QHJB 

Should it also work on the overview page?

**Comment by capoaira** [comment]
There are no caches on the overview page, so there is nothing to send.
