### ISSUE TITLE
Send to c:geo - Google store

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#7]
_From @Cu8eR on August 10, 2013 19:48_

Add send to c:geo script to Google store and Mozilla store.

It would be nice to add this script to these stores... it would be update automatically, users could write their reviewes, etc... mainly no problem with installing

for example GC little help is in the Google store too

_Copied from original issue: cgeo/cgeo#3130_

**Comment by Lineflyer** [comment]
_From @JavaJens on August 11, 2013 16:52_

About the Mozilla "store", I try to package everything in an Addon in PR #3101 
For the Chrome Store I believe you have to pay a One-Time fee, prior to releasing a first App. So maybe someone with an Account could do this. 

I would be willing to maintain these addons.

**Comment by Lineflyer** [comment]
We already discussed about that in #1929 .
We have $5, that is no problem.

If you are willing to maintain it, thats a good thing.
But I think the project leader @mucek4 should hold all these account ownerships.

**Comment by Lineflyer** [comment]
_From @JavaJens on August 31, 2013 20:51_

Are there any updates to this or #3094 / #3101 ?
Cheers!

**Comment by Lineflyer** [comment]
_From @Bananeweizen on September 1, 2013 8:11_

@mucek4 Can you please look at registering an account in the Chrome Web Store?

**Comment by Lineflyer** [comment]
Seems it is time now to register at the Chrome Web Store because of this:
http://chrome.blogspot.co.uk/2014/05/protecting-chrome-users-from-malicious.html

@mucek4 You are in the US?! Can you still register there or shall I take a look to register and transfer the login details, etc. to you?

**Comment by Lineflyer** [comment]
A lot of mails and some posts on facbeook regarding that. Seems the Chrome version banning thirs party scripts is available now.

**Comment by Lineflyer** [comment]
@JavaJens Do I understand you correct, that your already merged initial commit for a Firefox add-on would work as well as input for the Google Chrome store?
If you could provide a "ready to upload" version I am willing to test and try to arrange with @mucek4 that we created an dev account and upload it.

**Comment by Lineflyer** [comment]
_From @JavaJens on June 8, 2014 20:15_

Should I create PR than or how would you like to receive everything? The
problem with Chrome is that it needs to be signed and so on....

**Comment by Lineflyer** [comment]
_From @JavaJens on June 8, 2014 20:17_

@Lars Currently I have a Chrome version with all three scripts GC, OC,
OcPl. However this needs to be signed by the person with the account I
think. But don't know exactly. Maybe I could send you the signed Version
with a dev certificate?

As for the FF version I have to look into that on how to deal with the
three scripts. It has been a while since I originally had the idea and did
the work on that.

**Comment by Lineflyer** [comment]
@JavaJens I am the wrong person to answer certificate questions. Maybe some developer can answer that?! You may also join our channel #cgeo on freenode IRC to get some answers.

**Comment by Lineflyer** [comment]
@mucek4 Once you returned, can you please take a look at the Chrome Store to create an account for us?

**Comment by Lineflyer** [comment]
Here is a brief description:
https://developer.chrome.com/webstore/get_started_simple

**Comment by Lineflyer** [comment]
_From @JavaJens on June 13, 2014 8:54_

Relevant would be everything from:
https://developer.chrome.com/webstore/get_started_simple#step5
And Step 4 for developers who want to test the app locally.

**Comment by Lineflyer** [comment]
_From @GenaBitu on June 13, 2014 9:44_

Send2 c:geo just ceased to work for me - was automatically disabled by chrome and can not be enabled again - because it's not from the store

**Comment by Lineflyer** [comment]
_From @rsudev on June 13, 2014 9:48_

@GenaBitu  I could say 'use a decent browser that gives you the freedom to decide and doesn't overrule your decisions', but as you see, we are already working on this.

**Comment by Lineflyer** [comment]
@mucek4 Did yo find time to do this?

**Comment by Lineflyer** [comment]
_From @JavaJens on July 19, 2014 10:40_

I guess we can close this than as well?

**Comment by Lineflyer** [comment]
_From @SammysHP on July 19, 2014 14:25_

Is it already published?

**Comment by Lineflyer** [comment]
_From @JavaJens on July 19, 2014 14:44_

I dont know, but mucek has a PR for that afaik.

**Comment by Lineflyer** [comment]
_From @mucek4 on July 20, 2014 8:52_

Nobody has time to check it.

**Comment by Lineflyer** [comment]
This needs to become more urgent due to new restrictions in Chrome. From support mail:

I would like to ask you for one thing for improvement. 
I had tried to install plugin send2cgeo into my Chrome browser and it was working well but only until first restart of my browser. After that Chrome automatically blocked all plugins which are not from official chrome store with explanation that it is not allowed to install plugins out of chrome official store. 
It is standard chrome security setting in last versions. 
Would be possible to add your plugin into the Chrome store?

**Comment by Lineflyer** [comment]
As we now have a well working description of how to use Tampermonkey in combination with Google Chrome for send2cgeo, publishing the script in the Google Store is obsolete.

**Comment by GenaBitu** [comment]
I don't quite get the mess of moving this isuue, but why use the Tampermonkey addon, when it could be installed directly (AFAIK, I haven't done any extensions for a long time...)?

**Comment by Lineflyer** [comment]
Because it would cost money and produce more dependencies and more things to maintain.
Technically the Tampermonkey solution provides exactly the same functionality.
