### ISSUE TITLE
send2cgeo button has disappeared from cache page.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/send2cgeo#72]
Hi there,
I no longer see the send2cgeo button on a cache page.

I'm running Chrome 79.0.3945.130 
TamperMonkey v4.9
send2cgeo 0.46

**Comment by bekuno** [comment]
This problem is already fixed (issue #62)
Please test it by updating the script using
https://github.com/cgeo/send2cgeo/raw/master/send2cgeo.user.js
