### ISSUE TITLE
New send2cgeo release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/send2cgeo#73]
Can someone enlighten me, whether `master` has a stable condition to merge it to `release` to trigger update on user side?
I have seen some commits, some issues, but missing the time to get the conclusion right now.

**Comment by bekuno** [comment]
fixed/changed:
* gc.com
  #62 / #64 no send2cgeo button over all 
  #65 / #67 list view with doubled icon
  - / #60 send2cgeo button look like download gpx button
* ocpl
  - / #61 https

This is better than before, esp. issue #62

I would at leaset integrate the open PR's before a new release.

**Comment by Lineflyer** [comment]
I did not follow or test recent merges.
So please inform here, if you think current `master` is good enough to fix the regression and confirmed working for the legacy functions.
We can do more improvement later on, but the current `release` is broken, therefore I would like to release rather soon.

**Comment by bekuno** [comment]
Now all open PR are merged. 
I updated the list in https://github.com/cgeo/send2cgeo/issues/73#issuecomment-576875181
Not all broken things are fixed (esp. #66), but this will take some time now.

@Lineflyer I think you should release now.

**Comment by Lineflyer** [comment]
I will merge master to release tonight.Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Bernd <notifications@github.com> Datum: 28.01.20  23:47  (GMT+01:00) An: cgeo/send2cgeo <send2cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Mention <mention@noreply.github.com> Betreff: Re: [cgeo/send2cgeo] New send2cgeo release (#73) Now all open PR are merged.
I updated the list in #73 (comment)
Not all broken things are fixed (esp. #66), but this will take some time now.
@Lineflyer I think you should release now.

**Comment by Lineflyer** [comment]
branch master has been merged to release, thus v0.48 should be live and available to users now
