### ISSUE TITLE
s2cgeo does't work on recentlyviewed and nearest list

### ISSUE THREAD

**Issue by capoaira** [cgeo/send2cgeo#77]
I think it's because there is no "Send to GPS" button, so the s2cgeo button isn't added.

**Comment by simrebel** [comment]
having same issue  multiple computers  firefox  and chrome   tampermonkey says the script is running  but no button showing up on any cache pages ,

**Comment by capoaira** [comment]
I will take a look at this next week.

**Comment by bekuno** [comment]
@simrebel The problem you describe is #72.
This is fixed and the new version will released soon. In the meantime you can try the  code from master branch.

**Comment by simrebel** [comment]
cool  the script https://github.com/cgeo/send2cgeo/raw/master/send2cgeo.user.js    fixed the problem :)
