### ISSUE TITLE
GCLH2 does not work while send2cgeo got new update

### ISSUE THREAD

**Issue by Cachemichl** [cgeo/send2cgeo#81]
Today i got the update from sent2cgeo and now my GCLH2 does not work any longer.
If i stop the send2cgeo-Script everything is ok.
Please check

Win10, Firefox 72.0.2

**Comment by capoaira** [comment]
Please open the console and add a screenshot. Which error message you get?

**Comment by bekuno** [comment]
On which type of website is the problem (cache detail, list view, map, ...)?

**Comment by Cachemichl** [comment]
> 
> 
> Please open the console and add a screenshot. Which error message you get?

There is no error message. GCLH2 is just not working at the listing page and don's stop searching the log entrys

**Comment by Cachemichl** [comment]
> 
> 
> On which type of website is the problem (cache detail, list view, map, ...)?

On the normal listing website.
GCLH2 shows no friend list, no logs, no icon on the top...
Looks like the whole GCLH2 is blocked by send2cgeo.
If i deaktivate it, everything works fine. Ans it worked fine together until the update today

**Comment by capoaira** [comment]
I want to look at this coming WE or next week.

**Comment by capoaira** [comment]
With my Android Firefox it works everything fine. I try to reproduce the bug on my windows PC...

**Comment by Cachemichl** [comment]
![Ashampoo_Snap_2020 01 30_22h37m35s_001_](https://user-images.githubusercontent.com/60474325/73492635-60c4bd00-43b1-11ea-9d7d-b81a54983c75.jpg)

**Comment by Cachemichl** [comment]
OMG... It starts to get really complicated. Also to me to describe with my school english and User-PC-scills....
OK, let's try...
In my Firefox there is also uBlock running with "cookiebot.com".
If i stop uBlock, sent2cgeo and GCLH2 work together but the lower/second detail map is not displayed.
If uBlock runs, both maps are displayed but the logs are still loading and GCLH2 is waiting for the logs to work with it.

**Comment by Lineflyer** [comment]
In which sequence is Tampermonkey configured to run the scripts of GCLH and SEND2CGEO?

**Comment by capoaira** [comment]
> Also to me to describe with my school english and User-PC-skills....

Ich habe kein Probelm wenn du auf Deutsch schriebst. Das spart auch mir den Google Übersetzer 😉
Es ist für den GClh nicht mehr nötig cookiebot.com zu blockieren. Es sind nicht mehr viele Bugs die da durch entstehen. 
Ich weiß gerade nicht wie der stand bei anderen userscripten ist. Ich meine GCTour läuft auch ohne normal.
Wenn du keine anderen Scripte nutzt würde ich auf das blockieren verzichten. Ich denke anderes können wir das Problem nicht lösen.

> In which sequence is Tampermonkey configured to run the scripts of GCLH and SEND2CGEO?

I think there are no differences. I try it in both directions and it works without uBlock. (I can not test it with uBlock in this Moment)

**Comment by bekuno** [comment]
to cookiebot see here, first point:
https://github.com/2Abendsegler/GClh/blob/collector/docu/changelog.md#v0102

**Comment by Cachemichl** [comment]
Hurra!!!! Kein Englischgestammel mehr!!
Jedenfalls, wenn ich den uBlock ANschalte, send2cgeo UND GCLH2 AN habe dann sehe ich im Listing beide Karten, die Logs werden jedoch nicht geladen und alle GCLH-Funktionen die darauf basieren laufen nicht.

Wenn ich uBlock AUS und send2geo UND GCLH2 AN mache laden die Logs, jedoch wird die untere Karte nicht angezeigt und bleibt leer.

Sobald ich send2cgeo ausschalte funktioniert alles problemlos miteinander, so wie auch vor dem Update.

Irgendetwas ist da wohl doch noch mit "cookiebot.com".
Hauptproblem ist aber IMHO die Veränderung im heutigen Update von send2cgeo

**Comment by capoaira** [comment]
Ah stimmt. Die untere Karte hat Probleme mit jQuery (das selbe Problem was wir auf der Browse Map (alten Karte) haben #66). Das zerschießt mir auch manmal alle funktionen in den Cachedetails.

Wenn ich wieder Zuhause bin setzte ich mich nochmal da ran und versuche das zu lösen.

**Comment by Cachemichl** [comment]
Top!! zumindest konnte ich Beitragen den Fehler zu finden

**Comment by mirek454** [comment]
Script send to c:ge works ONLY on a new map. Please correct so that it works on the old map.

**Comment by capoaira** [comment]
I'm working on it. We already know about this bug (#66)
Please check if there is already an issue about the bug before you post it somewhere!

**Comment by capoaira** [comment]
Hello,
I think I have found a solution. Please check if it's also fixes your problems.
Here the test script: https://github.com/capoaira/send2cgeo/raw/jQueryTest/send2cgeo.user.js

To get automatic updates again, please install the current release after you finish the test: https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js

**Comment by Cachemichl** [comment]
Also ich habe das Skript getestet und es funktionierte wieder Alles.
Danach habe ich laut Beschreibung auf den zweiten Link geklickt und es klappt immer noch Alles.
Welche Version aber mittlerweile installiert ist kann ich nicht erkennen.
Meine beschriebenen Probleme sind jedoch erstmal behoben. Mit uBlock an oder aus.
Das Einzige was mir aufgefallen ist ist dass beim Klick auf den s2cg-Button keine Hand sondern ein "Text einfügen" Icon erscheint.
Wie kann ich nun erkennen ob ich wieder die reguläre Updatefähige Version installiert habe?
DANKE für den Support soweit übrigens!!!

**Comment by Cachemichl** [comment]
Nachtrag: Habe in den Einstellungen Hinweise auf Version 0.48 entdeckt

**Comment by capoaira** [comment]
Erkennen kannst du das nur wenn du den code vergleichst.
Dir aktuelle Version ist https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js wenn du den Link anklickt kannst du auf neu installieren klicken und dann hast du die aktuelle Version. 
Wenn du die installiert hast, wird alles so wie vorher sein, aber mit dem nächsten update werden die Fehler dann behoben.
Das mit dem Mauszeiger werde ich überarbeiten.

**Comment by Cachemichl** [comment]
Gibt's was Neues? Anything new?

**Comment by capoaira** [comment]
Die PR verändert viel und wird deswegen noch ausführlicher geprüft. 
Ich hoffe, das es dannach schnell eine neue Release gibt.

**Comment by Cachemichl** [comment]
Vielen Dank für die Info. Ich wollte nicht drängeln, nur nachfragen da ich nicht sicher bin ob man die Updates auch automatisch bekommen wenn das Skript deaktiviert ist.

**Comment by capoaira** [comment]
Ich weiß es zwar nicht, bin mir aber sicher, das es das Update immer gibt.

**Comment by Cachemichl** [comment]
Warum wurde das hier geschlossen opbwohl der Fehler immer noch auftritt und es kein Update gab?
Oder hätte ich selbst etwas updaten müssen?

**Comment by capoaira** [comment]
Die PR die den Fehler behebt wurde in den Masterbranch germerged, allerdings noch nicht in den releasebranch. Im master werden sozusagen alle Neuerungen und Fixes gesammelt, bevor sie an die User weitergegeben werden. 
Ich kann leider kein neues release erstellen. Da müssen wir auf @Lineflyer warten.

Geschlossen wird der Issue immer nach dem merge. Damit ist dann klar, das er im nächsten Release gefixt/umgesetzt wurde. Es dient der Übersicht.

**Comment by Cachemichl** [comment]
Vielen Dank für die kompetente Erklärung. Macht Sinn

**Comment by Cachemichl** [comment]
Kurzes Feedback:
Das Update wird nicht automatisch gemacht wenn das Skript nicht angeschalten ist.
Auch bei Updatesuche wurde nichts vorgheschlagen.
Sobald aber unter dem Tampermonkeyicon der Schalter auf "an" gelegt wurde zog es das Update automatisch

**Comment by capoaira** [comment]
Interessant.
Auch bei mir hat es sich nicht sofort automatisch upgedatet, obwohl ich das Script an hatte. Erst heute. Scheint also nicht so zuverlässig zu funktionieren.

**Comment by Lineflyer** [comment]
Danke fürs Feedback. Das ist das normale Verhaten von Tampermonkey. Deaktivierte Scripts werden bei keiner Aktion berücksichtigt.

**Comment by bekuno** [comment]
Beide Punkte lassen sich konfigurieren, siehe die Tampermonkey Einstellungen:
![grafik](https://user-images.githubusercontent.com/32555742/75091029-4c678080-5569-11ea-97f8-12d49b9244dd.png)

**Comment by capoaira** [comment]
Ah, das wusste ich auch noch nicht. Das erklärt aber, warum er bei mir erst so spät das update gemacht hat.

**Comment by Cachemichl** [comment]
Auch ich bedanke mich für die Info
