### ISSUE TITLE
Non-functional change of coordinates

### ISSUE THREAD

**Issue by Loskatos** [cgeo/send2cgeo#82]
You cannot change coordinates when the script is on. nothing happens when you click Accept. Tested on multiple geocaches. Everything is OK after turning off the script.

**Comment by capoaira** [comment]
This is the same Issue than #66 and #81. Sometimes the script crash the whole listingspage because of jQuery and the map.

**Comment by Loskatos** [comment]
Well thank you. As I can see, it has not yet been resolved. I will hope. Thank you

**Comment by FriedrichFroebel** [comment]
I just did a quick test and writing `$.noConflict();` at the beginning of the user script and using `jQuery` instead of `$` elsewhere seems to work in this specific case (I have not tested the other stuff).

The error I get without this replacement (using the latest Firefox on Ubuntu):

```
17:03:48.273 TypeError: $.pageMethod is not a function GCXXXX_cache-name:1753:19
    buildCacheCoordMenu https://www.geocaching.com/geocache/GCXXXX_cache-name?guid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:1753
    jQuery 2
        dispatch
        handle 
```

**Comment by capoaira** [comment]
I tried it, but without success.
Where exactly did you use the `$ .noConflict ();`?

**Comment by FriedrichFroebel** [comment]
@capoaira I placed it right before the first variable declaration `s` in line 35.

**Comment by capoaira** [comment]
For me it doesn't work.

I get the following error message (at the cachedetails and at the browse map):

```
ReferenceError: setStaticMap is not defined
    <anonym> https://www.geocaching.com/geocache/GCYEB9_t-d-032-gotteshauser-st-jakobi-neustadt line 1 > scriptElement:330:17
    jQuery 2
        e
        t
```

**Comment by capoaira** [comment]
Hello,
I think I have found a solution. Please check if it's also fixes your problems.
Here the test script: https://github.com/capoaira/send2cgeo/raw/jQueryTest/send2cgeo.user.js

To get automatic updates again, please install the current release after you finish the test: https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js

**Comment by Loskatos** [comment]
Yes, it works! Thank you very much.
Good job!

**Comment by capoaira** [comment]
> Reinstallation from the first link works,
> it will stop working after reinstallation from the bottom adress. :-(

Yes, because it is not merged now. With the next release the bug will be fixed.
But if you install the first link, Tampermonkey will not recognize when a new version is released.

**Comment by Loskatos** [comment]
Thank you for your explanation and for working on the script!

**Comment by bekuno** [comment]
@Loskatos 
the script has the parameter
~~~
// @updateURL      https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js
// @version        0.48
~~~
Tampermonkey/Greacemonkey checkes at "@updateURL" if the "@version" is greater than the current version. If a new version is official released than the new one will get a new version number and *monkey will update the script.

**Comment by capoaira** [comment]
> Tampermonkey/Greacemonkey checkes at "@updateURL" if the "@Version" is greater than the current version. If a new version is official released than the new one will get a new version number and *monkey will update the script.

But after the last release the script updated not for me, I think, because I not had the script from the `// @downloadURL    https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js`

**Comment by bekuno** [comment]
@capoaira 
No, the @downloadURL was unchaged in the js.
But the version number was already increased during the development but not once more before release.

**Comment by capoaira** [comment]
Ah ok, that make sense ;-)
