### ISSUE TITLE
s2cg is not going past "register first"

### ISSUE THREAD

**Issue by wizard4u** [cgeo/send2cgeo#97]
Unable to use s2cg. "Register first" keeps popping up
Re registering does not help

Google Chrome is up-to-date
Version 80.0.3987.149 (Officiële build) (64-bits)
script version 0.49

**Comment by bekuno** [comment]
Please check if this helps:
https://www.cgeo.org/faq#send2-register-first

**Comment by wizard4u** [comment]
Thanx,
it did not help

**Comment by capoaira** [comment]
I can understand the problem, with Chrome it actually doesn't work for me either. But it works with Firefox without problems.
I think it is a Server related Issue.

**Comment by wizard4u** [comment]
Similar: in Chrome it does not work, in FireFox it works

**Comment by mucek4** [comment]
Could it be some new Chrome setting about 3rd party cookies?

**Comment by SammysHP** [comment]
Third party cookies are phased out. Also cookies are/will only be sent for the same scheme (http/http and https/https, but not for mixed content).

**Comment by alan666notb** [comment]
I have the same, it says "Register first" when trying to send a cache to cgeo,
I goto the register page and it's already registered.

**Comment by Lineflyer** [comment]
I just tested with Chrome Version 80.0.3987.149 (Offizieller Build) (64-Bit) and send2cgeo v0.49 and did not find any problem.

**Comment by Lineflyer** [comment]
@alan666notb @wizard4u 
- Please open a geoaching cache details page on your browser
- Click on the lock icon in front of the URL
- Select "cookie" and check whether send2.cgeo.org is listed under allowed or blocked cookies

**Comment by alan666notb** [comment]
I looked at the cookies,

- None are blocked

- the following have been set
  consentcdn.cookiebot.com
  geocaching.com
  www.geocaching.com
  google.com

When I go the the 'register' page (That says I'm registered)
- the following are set
  send2cgeo.rog
  www.cgeo.org

**Comment by mucek4** [comment]
>     * the following are set
>       send2cgeo.rog
>       [www.cgeo.org](http://www.cgeo.org)

Is the dot missing in your text or actually in cookie?

**Comment by alan666notb** [comment]
> > ```
> > * the following are set
> >   send2cgeo.rog
> >   [www.cgeo.org](http://www.cgeo.org)
> > ```
> 
> Is the dot missing in your text or actually in cookie?

yeah sorry, typo, the dot is there (And it's 'org', not 'rog') - send2.cgeo.org

**Comment by jenda69** [comment]
Same problem for me. Chrome 80.0.3987.149, 64-bit: send2.cgeo.org cookies are alowed, but I'm still getting Register first.
This message pops up in dev console though:
> A cookie associated with a cross-site resource at http://send2.cgeo.org/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

I checked app-storage-cookies and send2cgeo doesn't have anything in SameSite column.

**Comment by Lineflyer** [comment]
It seems we need to set an additional parameter for the cookie then in order to work in Chrome?
However I still wonder, why I can use it without a problem in the same version of Chrome. Could it be, that it only affects new registrations (cookies set with this version)?

**Comment by Lineflyer** [comment]
It keeps working for me in Chrome even with new registration/cookie.

@wizard4u 
Can you check if you really did not block third party cookies in chrome://settings/content/cookies ?

**Comment by wizard4u** [comment]
Version 80.0.3987.163 (Officiële build) (64-bits) and working again

**Comment by bekuno** [comment]
maybe only temporarily?
https://heise.de/-4697376

**Comment by Lineflyer** [comment]
This problem ssems to be back with recent Chrome version udpate.
To be investigated.

Several users on support mail

**Comment by Lineflyer** [comment]
@capoaira 
Anything we can do about this samesitecookie restriction from scrip side?

Otherwise I need to find out if the user can tweak this limitation via settings and create a FAQ entry.

**Comment by Lineflyer** [comment]
Another possibility would probably be to move away from using cookies. Refer to #12

**Comment by capoaira** [comment]
At this moment I have no idea, but I'm on vacation. Maybe I have a bit time in the evening.

**Comment by capoaira** [comment]
To fix the bug, I just have to allow all cookies. Then everything works without problems.

I don't think you can do much from the script side because the cookies are not set there.
To be honest, I have no idea of it.

**Comment by capoaira** [comment]
Maybe I have an idea but that is not "beautiful".
You can open and close windows using the script. Maybe we can open and close the add page. Then the cookies shouldn't be third-party cookies, should they?

**Comment by wizard4u** [comment]
allowing all cookies is not a solution in my case: no effect

**Comment by capoaira** [comment]
I made a **very experimental (!)** version. Please test whether this works: https://github.com/capoaira/send2cgeo/raw/chrome/send2cgeo.user.js
(only on the new map, single caches on the BML and CO dashboard. It is not implemented for the other.)
If that works for all, I implement this also for all buttons.

Go back to the current release version here: https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js

Then I would rewrite the script so that it always uses the function `buildButton()` and not `window.s2geo()`. This makes programming the script clearer.

Note for me:
https://stackoverflow.com/questions/1258563/how-can-i-access-the-dom-tree-of-child-window

**Comment by TomFFriedrich** [comment]
Geänderte Script Datei funktioniert soweit. Getestet mit: Version 84.0.4147.105 (Offizieller Build) (64-Bit)

**Comment by ush189** [comment]
I installed the experimental version, but it's still not working.

**Comment by capoaira** [comment]
> I installed the experimental version, but it's still not working. 

Hmm, ok. What are your cookie settings in chrome?
Did you only test the new map?

**Comment by ush189** [comment]
> > I installed the experimental version, but it's still not working.
> 
> Hmm, ok. What are your cookie settings in chrome?
> Did you only test the new map?

Cookies and 3rd party cookies are allowed and I can find some for geocaching.com and cgeo.org. 
I tried sending from the cache detail page, the map (I don't know what you mean with new map though) and from a list of mine (is this what you mean with BLM?). If I can test something else to help just tell me.

**Comment by capoaira** [comment]
I've update my branch so that it should be work at all buttons. Please install the script again: https://github.com/capoaira/send2cgeo/raw/chrome/send2cgeo.user.js

Go back to the current release version here: https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js

.
> the map (I don't know what you mean with new map though) and from a list of mine (is this what you mean with BLM?)

The new (search) map is https://www.geocaching.com/play/map/
I mean with BML https://www.geocaching.com/plan/lists

**Comment by ush189** [comment]
It works! There's a little PopUp for one sec and then I can import it.

**Comment by capoaira** [comment]
Ok, perfect.
Thanks for testing. I'm working to make the solution a bit more "beautiful"
But it could take a little longer because I'm on vacation.

**Comment by capoaira** [comment]
@Lineflyer: I don't know the server code, but I can't access the content of the send2.cgeo.org page. Is it possible to allow cross-orgin? Then it would be possible to show errors (like registering first) also with my workaround.

**Comment by capoaira** [comment]
Programming is much more fun than logging caches. So I was working on this issue yesterday and after a few minutes it was four hours later ... ups 🤣
I'm testing today and for me it works. **Please feel free to test it too**.
To use the "new way" you have to enable a setting. You'll find the Settings on the right side of the geocaching.com Dashboard (https://www.geocaching.com/account/dashboard) under "_Joined xxx_".

Here it goes to the new version: https://github.com/capoaira/send2cgeo/raw/chrome/send2cgeo.user.js
Go back to the current release version here: https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js

The settings can be also used for #14/#50 and for a button for #11

**Comment by capoaira** [comment]
The settings has to be also include to the opencaching page. But I don't know where. Maybe sombody here has an idea?

**Comment by capoaira** [comment]
Hello,
I have completed this issue - I think ;)
**Please test it**. Is everything clearly explained? Should anything else be added?

Here it goes to the new version: https://github.com/capoaira/send2cgeo/raw/cookie-problem/send2cgeo.user.js
After testing, please return to the current release version: https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js

**Comment by ush189** [comment]
Did you change something visible? Looks like the chrome version to me. Still working as soon as I activate the new setting. Maybe you can hint to the settings if someone is getting the "register first"? Or how are you supposed to know?

**Comment by capoaira** [comment]
> Did you change something visible?

I've changed the settings a bit and add a description, but my english is not the best ;)



> Maybe you can hint to the settings if someone is getting the "register first"? Or how are you supposed to know?

Unfortunately, without third-party cookies for the script, it is not possible to find out whether you are registered. For that you would need something like an api

**Comment by ush189** [comment]
> I've changed the settings a bit and add a description, but my english is not the best ;)

Ah, I overlooked the question mark :) Looks fine too me. 

> Unfortunately, without third-party cookies for the script, it is not possible to find out whether you are registered. For that you would need something like an api

If that's a problem for all chrome users, then maybe the new setting should be activated by default? But a hint on the help page would also do it I guess. 

But anyways, I'm just happy it's working again, so thanks for that! :)

**Comment by capoaira** [comment]
> If that's a problem for all chrome users, then maybe the new setting should be activated by default? But a hint on the help page would also do it I guess.

Not all chrome userer have that problem and not all useres use chrome. But a note on the send2cgeo page and/or the FAQ will definitely be added.

**Comment by TomFFriedrich** [comment]
This is peculiar. With the last version, send2cgeo reports in the overview that I am registered. If you want to use the function, "Register fist" appears. I cannot unregister. Why is that?

**Comment by capoaira** [comment]
Which browser you use?
If you delete your cookies you are unregistered. 
I think you also use Chrome? Chrome blocks all third party cookies, like send2cgeo. You can read my last comment https://github.com/cgeo/send2cgeo/issues/97#issuecomment-674576089
There I test a new version. Solved that your problem?

**Comment by alan666notb** [comment]
What is the 'Setting' you keep talking about?

I have the same problem that 'TomFFriedrich' posted above, on the overview page it says my browser is registered and named, but when I try to use send2cgeo it says 'Register first'

I'm using the 'new' script that you posted a few comments earlier.

**Comment by capoaira** [comment]
You'll find the settings on the new Dashboard (geocaching.com) under "joined at" or on "my home" (opencaching.de) at the top.

**Comment by TomFFriedrich** [comment]
Hi, that's it. THX
Look here. On the left side - this link

<img width="253" alt="ativateSend2cgeo" src="https://user-images.githubusercontent.com/69390259/90392493-3e656900-e08f-11ea-92ba-dd241fa1927b.png">

**Comment by wizard4u** [comment]
Hi All, the solution works for me. Many thanx
